# Topic 3: Filtering and Selection

## Topic
**Filtering and Selection** - Access and filter DataFrame rows and columns.

## Learning Goals
- Select columns by name
- Filter rows using boolean conditions
- Use `loc` and `iloc` for position/label-based selection
- Combine multiple conditions

## Questions
There are **5 questions** in this notebook, progressing from easy to moderate.

> **Instructions:** Write your solution in each `# Your Code Here` cell.

In [1]:
import pandas as pd
import numpy as np

In [2]:
# Base DataFrame for this topic
data = {
    'name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Evan'],
    'age': [25, 30, 35, 28, 40],
    'city': ['New York', 'London', 'Paris', 'Tokyo', 'Berlin'],
    'score': [88, 92, 85, 90, 95],
    'department': ['Sales', 'HR', 'Tech', 'Sales', 'Tech']
}
df = pd.DataFrame(data)
df

      name  age      city  score department
0    Alice   25  New York     88      Sales
1      Bob   30    London     92         HR
2  Charlie   35     Paris     85       Tech
3    Diana   28     Tokyo     90      Sales
4     Evan   40    Berlin     95       Tech

## Question 1 - Select Single Column
Select the `name` column and store it in `names`. Then select the `score` column and store it in `scores`.

In [4]:
# Your Code Here
names=df['name'].tolist()
scores=df['score'].tolist()
print(names)
print(scores)

['Alice', 'Bob', 'Charlie', 'Diana', 'Evan']
[88, 92, 85, 90, 95]

## Question 2 - Select Multiple Columns
Select columns `name`, `age`, and `city` as a new DataFrame and store in `selected_df`.

In [5]:
# Your Code Here
selected_df=df[['name','age','city']]
selected_df

      name  age      city
0    Alice   25  New York
1      Bob   30    London
2  Charlie   35     Paris
3    Diana   28     Tokyo
4     Evan   40    Berlin

## Question 3 - Filter Rows with Condition
Filter rows where `age > 28` and store in `filtered_df`.

In [3]:
# Your Code Here
filtered_df =df[df['age']>28]
filtered_df

      name  age    city  score department
1      Bob   30  London     92         HR
2  Charlie   35   Paris     85       Tech
4     Evan   40  Berlin     95       Tech

## Question 4 - Use loc and iloc
Using `loc`, get the row where `name == 'Diana'` and store in `diana_row`.  
Using `iloc`, get the 3rd row (index position 2) and store in `third_row`.

In [7]:
# Your Code Here
diana_row = df.loc[df['name'] == 'Diana']
third_row = df.iloc[2]
diana_row
third_row

name          Charlie
age                35
city            Paris
score              85
department       Tech
Name: 2, dtype: object

## Question 5 - Multiple Conditions
Filter rows where `department == 'Tech'` AND `score >= 90` and store in `tech_high_score`.

In [8]:
# Your Code Here
tech_high_score =df[(df['department']=='Tech' )& (df['score']>=90)]
tech_high_score

   name  age    city  score department
4  Evan   40  Berlin     95       Tech

## Summary
You practiced DataFrame selection and filtering with:
- Column selection: `df['col']` or `df[['col1', 'col2']]`
- Boolean filtering: `df[df['col'] > value]`
- `loc`: label-based selection
- `iloc`: position-based selection
- Multiple conditions: `(cond1) & (cond2)`

Next: Data manipulation and transformations.