# 📘 Topic 4: Adding & Dropping Columns and Rows

---

## 🗂️ Topic
**Adding & Dropping Columns/Rows** — Modifying the structure of a DataFrame.

## 🎯 Learning Goals
- Add new columns to a DataFrame
- Drop columns and rows
- Rename columns
- Reset and set index
- Insert columns at a specific position

## 📋 Questions
There are **5 questions** in this notebook, progressing from easy to moderate.

---
> **Instructions:** Write your solution in the `# ✏️ Your Code Here` cell below each question.  
> Run the **Verify** cell after each question to check your answer.

In [1]:
import pandas as pd
import numpy as np

---
## ❓ Question 1 — Basic

Start with this DataFrame:

```python
df = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie', 'Diana'],
    'age':  [25, 30, 35, 28]
})
```

Add a new column called `'salary'` with values `[50000, 60000, 70000, 55000]`.  
Print the updated DataFrame.

In [3]:
# ✏️ Your Code Here
df = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie', 'Diana'],
    'age':  [25, 30, 35, 28]
})
df['salary']=[50000,60000,70000,55000]
df

      name  age  salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   35   70000
3    Diana   28   55000

---
## ❓ Question 2 — Basic

Start with this DataFrame:

```python
df2 = pd.DataFrame({
    'name':    ['Alice', 'Bob', 'Charlie', 'Diana'],
    'age':     [25, 30, 35, 28],
    'country': ['USA', 'UK', 'France', 'Japan'],
    'temp':    [1, 2, 3, 4]
})
```

Drop the column `'temp'` from `df2` (modify in place or reassign).  
Print the updated DataFrame.

In [6]:
# ✏️ Your Code 
df2 = pd.DataFrame({
    'name':    ['Alice', 'Bob', 'Charlie', 'Diana'],
    'age':     [25, 30, 35, 28],
    'country': ['USA', 'UK', 'France', 'Japan'],
    'temp':    [1, 2, 3, 4]
})
df2 = df2.drop('temp', axis=1)
df2

      name  age country
0    Alice   25     USA
1      Bob   30      UK
2  Charlie   35  France
3    Diana   28   Japan

---
## ❓ Question 3 — Basic-Intermediate

Start with this DataFrame:

```python
df3 = pd.DataFrame({
    'name':  ['Alice', 'Bob', 'Charlie', 'Diana'],
    'age':   [25, 30, 35, 28],
    'score': [88, 45, 72, 39]
})
```

Drop all rows where `score < 50`.  
Print the resulting DataFrame (reset the index).

In [9]:
# ✏️ Your Code Here
df3 = pd.DataFrame({
    'name':  ['Alice', 'Bob', 'Charlie', 'Diana'],
    'age':   [25, 30, 35, 28],
    'score': [88, 45, 72, 39]
})
df3 = df3[df3['score'] >= 50].reset_index(drop=True)
df3

      name  age  score
0    Alice   25     88
1  Charlie   35     72

---
## ❓ Question 4 — Intermediate

Start with this DataFrame:

```python
df4 = pd.DataFrame({
    'nm':  ['Alice', 'Bob', 'Charlie'],
    'ag':  [25, 30, 35],
    'ct':  ['New York', 'London', 'Paris']
})
```

Rename the columns so that:
- `'nm'` → `'name'`
- `'ag'` → `'age'`
- `'ct'` → `'city'`

Print the renamed DataFrame.

In [10]:
# ✏️ Your Code Here
df4 = pd.DataFrame({
    'nm':  ['Alice', 'Bob', 'Charlie'],
    'ag':  [25, 30, 35],
    'ct':  ['New York', 'London', 'Paris']
})
df4=df4.rename(columns={'nm':'name','ag':'age','ct':'city'})
df4

      name  age      city
0    Alice   25  New York
1      Bob   30    London
2  Charlie   35     Paris

---
## ❓ Question 5 — Intermediate

Start with this DataFrame:

```python
df5 = pd.DataFrame({
    'name':  ['Alice', 'Bob', 'Charlie'],
    'age':   [25, 30, 35],
    'score': [88, 92, 85]
})
```

Insert a new column called `'grade'` with values `['A', 'A+', 'A']`  
at **position 2** (between `age` and `score`).  
Print the updated DataFrame.

In [11]:
# ✏️ Your Code Here
df5 = pd.DataFrame({
    'name':  ['Alice', 'Bob', 'Charlie'],
    'age':   [25, 30, 35],
    'score': [88, 92, 85]
})
df5.insert(2, 'grade', ['A', 'A+', 'A'])
df5

      name  age grade  score
0    Alice   25     A     88
1      Bob   30    A+     92
2  Charlie   35     A     85

---
## 🏁 Summary

You practiced modifying DataFrame structure with:
- Adding columns: `df['new_col'] = values`
- Dropping columns: `df.drop(columns=['col'])`
- Dropping rows by condition: `df[df['col'] > value].reset_index(drop=True)`
- Renaming columns: `df.rename(columns={'old': 'new'})`
- Inserting at a position: `df.insert(pos, 'col_name', values)`

➡️ **Next up: Topic 5 — Grouping & Aggregation**